name: 'Discord Notify Action'
description: 'Send a message to a Discord channel.'
author: cabrera-evil
branding:
  icon: 'message-circle'
  color: 'black'
inputs:
  webhook_url:
    description: 'Discord webhook URL'
    required: true
    default: ''
  title:
    description: 'Message title'
    required: false
    default: ''
  description:
    description: 'Message description'
    required: true
    default: ''
  include_image:
    description: 'If action is used in a pull request, attach the preview image for it to the card. Required for custom_image_url'
    required: false
    default: 'false'
  avatar_url:
    description: 'Custom avatar image URL'
    required: false
    default: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
  username:
    description: 'Custom username'
    required: false
    default: 'GitHub'
  color:
    description: 'Color for the edge of the card in hex'
    required: false
    default: '#24292e'
  custom_image_url:
    description: 'Include custom image on card, include_image must be true'
    required: false
    default: ''
  title_url:
    description: 'Make the title of the card a link'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.webhook_url}}
    - ${{inputs.title}}
    - ${{inputs.description}}
    - ${{inputs.include_image}}
    - ${{inputs.avatar_url}}
    - ${{inputs.username}}
    - ${{inputs.color}}
    - ${{inputs.custom_image_url}}
    - ${{inputs.title_url}}
