services:
  action:
    build:
      context: .
      dockerfile: Dockerfile
    image: cabreraevil/discord-notify-action
    container_name: discord-notify-action
    restart: no
    environment:
      INPUT_WEBHOOK_URL: '${INPUT_WEBHOOK_URL}' # Required
      INPUT_TITLE: ${INPUT_TITLE} # Optional
      INPUT_DESCRIPTION: ${INPUT_DESCRIPTION} # Required
      INPUT_AVATAR_URL: ${INPUT_AVATAR_URL} # Optional
      INPUT_USERNAME: ${INPUT_USERNAME} # Optional
      INPUT_URL: ${INPUT_URL} # Optional
      INPUT_COLOR: ${INPUT_COLOR} # Optional
      INPUT_STATUS: ${INPUT_STATUS} # Optional
      INPUT_ENVIRONMENT: ${INPUT_ENVIRONMENT} # Optional
      INPUT_INCLUDE_IMAGE: ${INPUT_INCLUDE_IMAGE} # Optional
      INPUT_CUSTOM_IMAGE_URL: ${INPUT_CUSTOM_IMAGE_URL} # Optional
      INPUT_REPO_NAME: ${INPUT_REPO_NAME} # Optional
      INPUT_REPO_URL: ${INPUT_REPO_URL} # Optional
      INPUT_COMMIT_MESSAGE: ${INPUT_COMMIT_MESSAGE} # Optional
      INPUT_COMMIT_SHA: ${INPUT_COMMIT_SHA} # Optional
      INPUT_AUTHOR: ${INPUT_AUTHOR} # Optional
    command:
      - $INPUT_WEBHOOK_URL
      - $INPUT_TITLE
      - $INPUT_DESCRIPTION
      - $INPUT_AVATAR_URL
      - $INPUT_USERNAME
      - $INPUT_URL
      - $INPUT_COLOR
      - $INPUT_STATUS
      - $INPUT_ENVIRONMENT
      - $INPUT_INCLUDE_IMAGE
      - $INPUT_CUSTOM_IMAGE_URL
      - $INPUT_REPO_NAME
      - $INPUT_REPO_URL
      - $INPUT_COMMIT_SHA
      - $INPUT_AUTHOR
