services:
  action:
    image: cabreraevil/discord-notify-action:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    command:
      ['A new commit has been pushed to cabrera-evil/discord-notify-action.']
    env_file:
      - .env
