name: Discord Notify

on:
  push:
    tags:
      - '1.0.2'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        uses: cabrera-evil/discord-notify-action@1.0.2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: 'GitHub Action'
          description: 'A new commit has been pushed.'
          include_image: 'true'
          username: 'GitHub'
          title_url: 'https://github.com/${{ github.repository }}/commit/${{ github.sha }}'
