name: Discord Notify

on:
  push:
    branches:
      - master

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: cabrera-evil/discord-notify-action@feature/embed-message-params
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: 'GitHub Action'
          description: 'A new commit has been pushed to the master branch.'
          include_image: 'true'
          username: 'GitHub'
          title_url: 'https://github.com/${{ github.repository }}/commit/${{ github.sha }}'
